### ISSUE TITLE
No Logs or Traces in Application Insights

### ISSUE THREAD

**Issue by shrikantdatke** [aliyoussefi/MonitoringPowerPlatform#4]
Hello Ali,

I have followed all the steps given in this document, but I see no traces or Logs visible in Application Insights. I am sure I have properly added Instrumentation Key in the Power Apps, App Object.

I have been waiting for more than 2 hours, but no logs or events visible. I even don't see the Users in Usage instead I see "Your app needs to send custom events or page views to Application Insights to use these tools."

What I am really missing here? Can you please help?

**Comment by aliyoussefi** [comment]
Hi @shrikantdatke, Have you published and run the app from the player? If so, then it should send events when you navigate between screens of when you load the app initially. If you have a tool like Fiddler that can examine requests sent from the player you should see the requests go out from the player. If there are issues, the response will respond back with no items accepted which would indicate an additional issue.

**Comment by shrikantdatke** [comment]
Hello Ali,

Sorry for the late reply, yes the issue is resolved. I got a good help and understanding of the issue from Aengus. I will close this call.

**Comment by aliyoussefi** [comment]
Hi @shrikantdatke Sounds good, if you have any feedback I can provide the team please let me know and I will forward to the team!
