### ISSUE TITLE
Discuss: Power Platform Connections and Managed Solutions

### ISSUE THREAD

**Issue by aliyoussefi** [aliyoussefi/MonitoringPowerPlatform#7]
Hi Ali, I read your blog on the solution aware deep dive. So far you have come closest to the big puzzle I'm facing. 
Ideally we move solutions as managed to production environment. But you always have to change/update the connection. This creates a unmanaged layer on top preventing new updates.
Any thoughts on how we could control this without creating the unmanaged solution layer?

**Comment by aliyoussefi** [comment]
@mglat I'm reviewing my notes and will try to pick up where I left off.
While I setup to see about a workaround I will mention that a update to the platform will address this.
Until then and with minimal info let's work on this together. When I find my notes I'll create an issue branch that we can use to track.
Thanks!

Ali

**Comment by aliyoussefi** [comment]
Hi @mglat ,

I'm happy to report that yesterday the public preview for a feature that should remediate this has finally be announced: https://powerapps.microsoft.com/en-us/blog/announcing-the-new-solution-import-experience-with-connections-and-environment-variables/?_lrsc=ebd5d3b3-48fa-4dff-9a3d-f421cb6ff71b

I checked this internally and it works well, I'll try to report my findings and update the blog post soon.

Thanks!

Ali

**Comment by mglat** [comment]
Thanks, that is great news. 
Looks very promising
